#test DB 설정

spring:
  datasource:
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create
        globally_quoted_identifiers: true
  h2:
    console:
      enabled: true
